const Koa = require('koa')
const asset = require('koa-static')
const router = require('koa-router')()
const app = new Koa();

const entry = require('./dist/bundle').entry.default
const setupDevServer = require('./build/setup-dev-server')
app.use(async (ctx, next) => {
  const start = Date.now();
  await next();
  const ms = Date.now() - start;
  ctx.set('X-Response-Time', `${ms}ms`)
})

// let indexHTML // generated by html-webpack-plugin
// let renderer // created from the webpack-generated server bundle

// setupDevServer(app, {
//   bundleUpdated: bundle => {
//     renderer = createRenderer(bundle)
//   },
//   indexUpdated: index => {
//     indexHTML = parseIndex(index)
//   }
// })

// app.use(asset(__dirname + '/dist', {
//   extensions: ['js']
// }))

function render(template) {
  return `<!DOCTYPE html>
  <html lang="zh-CN">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Koa2-server</title>
  </head>

  <body>
    <div id="root">${template}</div>
    <script src="/bundle.client.js"></script>
  </body>

  </html>`
}

// add url-route:
router.get('/', async (ctx, next) => {
  var name = ctx.params.name;
  let html = entry(ctx.request.path)
  ctx.response.body = render(html)
});

// add router middleware:
app.use(router.routes())

app.listen(3000)